server:
  port: 2333
  address: 127.0.0.1

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 1
    gc-warnings: true
    rateLimiter:
      strategy: "rotateOnFail"
      searchTriggersFail: true
      ratelimit: 20

plugins:
  youtube:
    enabled: true
    allowSearch: false
    download: true

logging:
  level:
    root: WARN
    lavalink: WARN
    dev.lavalink.youtube: INFO
  logback:
    encoder:
      pattern: "%d{HH:mm:ss} [%logger{0}] %msg%n"
